### ISSUE TITLE
Can you change the syntax of highligh?

### ISSUE THREAD

**Issue by cnut1648** [sethyuan/logseq-plugin-wrap#1]
Hi, thanks for your plugin!!

I am wondering if it's possible to change the syntax. For example, right now the red highlight is this
```
[[#red]]==things to highlight==
```
but this will pollute the page `red`, and similar for `green` and `blue`. I'm not sure if this is easy to change the syntax but it would be great if it can.

Thanks again!

**Comment by sethyuan** [comment]
For technical reasons, the syntax I offered is considered by me the best solution for highlighting for now. Different than other solutions, it allows you to have other styles within the highlighted text, behaving just like the standard markdown highlight.

Also, the side-effect of tagging the block is not considered a “pollution” to me. In fact, I can make queries that extract blocks that are highlighted differently for different reasons. E.g. red for what A says, green for what B says, like that. 

That being said, you can always modify how wrapping goes by defining your own templates, you can find more information in README.

**Comment by cnut1648** [comment]
Oh I see. Makes sense! Thanks for the insight!
