### ISSUE TITLE
Trailing whitespace in wrapped content will cause render failure

### ISSUE THREAD

**Issue by JJAYCHEN1e** [sethyuan/logseq-plugin-wrap#11]
`[[#red]]==meaningful referent ==`
<img width="572" alt="image" src="https://user-images.githubusercontent.com/31304335/163316005-1d9ec68f-ce9f-4e1b-be56-afc282c9cffe.png">

**Comment by sethyuan** [comment]
The parsing of highlights is implemented by Logseq itself, I'd suggest you create an issue there, there is nothing I can do on the plugin side.

**Comment by JJAYCHEN1e** [comment]
@sethyuan Maybe we can leave whitespaces out of `==` when we generate it. I tested this method, it seems to work:

```js
  const start = textarea.selectionStart
  const end = textarea.selectionEnd
  let before = textarea.value.substring(0, start)
  let selection = textarea.value.substring(start, end)
  let after = textarea.value.substring(end)

  const trimRegex = /^(\s*).*?(\s*)$/
  const match = selection.match(trimRegex)
  const startWhitespaces = match[1]
  const endWhitespaces = match[2]
  before = before + startWhitespaces
  after = endWhitespaces + after
  selection = selection.trim()
```

**Comment by sethyuan** [comment]
No, what's inside `==` should be up to the user, plugin should not alter this selection. In fact, this is the parsing behavior of Logseq whether you use the plugin or not. If this behavior needs to change, it needs to happen on the Logseq part.

**Comment by JJAYCHEN1e** [comment]
> No, what's inside `==` should be up to the user, plugin should not alter this selection. In fact, this is the parsing behavior of Logseq whether you use the plugin or not. If this behavior needs to change, it has to happen on the Logseq part.

Maybe you can make it an option to auto trim the content(as Logseq doesn't fix it now), I think for many users highlight empty content is meaningless(and impossible now). I've been using this plugin for less than one day, but I accidentally select trailing whitespaces(using mouse) many times, which will cause rendering failure of the whole block. And I'll create an issue for Logseq.

**Comment by JJAYCHEN1e** [comment]
> > No, what's inside `==` should be up to the user, plugin should not alter this selection. In fact, this is the parsing behavior of Logseq whether you use the plugin or not. If this behavior needs to change, it has to happen on the Logseq part.
> 
> Maybe you can make it an option to auto trim the content(as Logseq doesn't fix it now), I think for many users highlight empty content is meaningless(and impossible now). I've been using this plugin for less than one day, but I accidentally select trailing whitespaces(using mouse) many times, which will cause rendering failure of the whole block. And I'll create an issue for Logseq.

I decide not to create an issue for Logseq. Most logseq users won't write something like `==a ==` to highlight the content, this issue only exist when we use this plugin's toolbar.

**Comment by sethyuan** [comment]
It has no direct relationship with the plugin. E.g, you can type `==` on a text selection in Logseq and you will observe the same behavior.

This plugin provides wrapping features, and for a wrap operation, no content replacements should be performed, it's principle. In the case of handling the last space character, just trimming it is not sufficient, we'd also need to append it after the wrap operation, but this is not a requirement general enough to apply to all wrapping cases, therefore should not be enforced.

**Comment by JJAYCHEN1e** [comment]
> It has no direct relationship with the plugin. E.g, you can type `==` on a text selection in Logseq and you will observe the same behavior.
> 
> This plugin provides wrapping features, and for a wrap operation, no content replacements should be performed, it's principle. In the case of handling the last space character, just trimming it is not sufficient, we'd also need to append it after the wrap operation, but this is not a requirement general enough to apply to all wrapping cases, therefore should not be enforced.

In my observation, logseq will auto trim the selected content when press `=`.

**Comment by sethyuan** [comment]
@JJAYCHEN1e This is implemented, can you try it if this is what you want.
