### ISSUE TITLE
修改 logseq-wrap.json 没有作用

### ISSUE THREAD

**Issue by ANNOARK** [sethyuan/logseq-plugin-wrap#13]
1. 通过 Logseq-Plugin-“open setting” 打开了 logseq-wrap.json 文件（文件中只有`{}`）。
2. 将提供的另一套设置（有加粗斜体的那个）贴入，保存后 Logseq 中并没有变化，浮动栏中显示的还是第一套的图标。

**Comment by ANNOARK** [comment]
重启Logseq没有用，但是适逢Logseq升级，安装后新的设置就生效了🤔

**Comment by sethyuan** [comment]
在改变插件配置后要重启一下Logseq才能应用起来。
