### ISSUE TITLE
[Feature Request] Add the option to not show icons

### ISSUE THREAD

**Issue by Theigrams** [sethyuan/logseq-plugin-wrap#18]
My json configuration file is as follows.
```json
"wrap-math-equation": {
    "label": "Wrap with math equation",
    "binding": "ctrl+m",
    "template": " $$^$ "
  },
"wrap-math-block": {
  "label": "Wrap with math block",
  "binding": "ctrl+shift+m",
  "template": "$$\n$^\n$$"
  }
```

However, the default icon displayed is "X", can we add an option in the json to control whether to display this icon or not ?
<img width="553" alt="image" src="https://user-images.githubusercontent.com/26341831/175773201-2a817ad5-6d37-4464-a638-d238593016fb.png">

**Comment by sethyuan** [comment]
Feature implemented, please have a try. The current behavior is if you don't configure an icon, it will not be displayed in the toolbar.

**Comment by Theigrams** [comment]
It works nice, thanks a lot!
