### ISSUE TITLE
The  position of the menu bar is out of vision when in the pdf view mode

### ISSUE THREAD

**Issue by WaytrueDeng** [sethyuan/logseq-plugin-wrap#2]
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/61548208/153988785-b3bcf85c-7381-45bc-a9da-ba4f2cc3b618.png">

**Comment by sethyuan** [comment]
感谢报告，我空下来的时候调查一下。

**Comment by sethyuan** [comment]
已经fix了，请尝试新版本。 @WaytrueDeng

**Comment by sethyuan** [comment]
不客气！
