### ISSUE TITLE
你好，请问一下是否可以使用 query 查找特定颜色的标记？

### ISSUE THREAD

**Issue by masonfocus** [sethyuan/logseq-plugin-wrap#20]
你好，请问一下是否可以使用 query 查找特定颜色的标记？

如果可以的话，要怎么操作呢？

**Comment by sethyuan** [comment]
可以的，查找颜色对应的标签就可以了，例如 `[[#red]]==红色内容==，其它文字。`，可以看到标签就是`#red`，也就是查询这个标签就可以了。如果要查找某个特定页面内的所有红色高亮可以参考以下查询：

```
{{query (and <%current page%> [[#red]])}}
```

`<%current page%>`代表当前页面，可以替换为某个具体的页面。

**Comment by masonfocus** [comment]
十分感谢，这样作用更大了。
