### ISSUE TITLE
关于 icon 如何选择？

### ISSUE THREAD

**Issue by masonfocus** [sethyuan/logseq-plugin-wrap#21]
你好，请问一下， icon 怎么定制呢？不太懂编程，恳请大佬赐教，调整pid的部分就可以找到对应 icon 吗？那各个 icon 的 id 怎么查看呢？

**Comment by sethyuan** [comment]
并不是哈，这里的icon是svg格式的图标。网上有人会发布一些免费的图标，你可以去找找。

**Comment by candideu** [comment]
@masonfocus : I used Google Material Icons: https://fonts.google.com/icons

I searched for the icon I needed, clicked on it, then selected "save SVG". If you open it in Notepad or in your browser (with Inspect Element), you should be able to grab the SVG code.

Make sure to escape the characters for JSON using something like this: https://www.freeformatter.com/html-escape.html#before-output

To change the colour, add a fill attribute like this: `<svg fill="#fff"`

**Comment by sparkles6452** [comment]
@candideu Thanks for dropping a hint on how-to handle custom SVGs.

I used https://fontawesome.com/search?o=r&m=free.
