### ISSUE TITLE
在solarized extended theme主题中会出现工具栏遮挡文字的情况

### ISSUE THREAD

**Issue by jayus71** [sethyuan/logseq-plugin-wrap#22]
- solarized extended theme主题的效果
![solarized extended theme](https://user-images.githubusercontent.com/62584977/185555463-837b163d-f725-4ef6-81e3-2b96d3a09db0.png)
----------
- dev theme主题的效果
![dev theme](https://user-images.githubusercontent.com/62584977/185555505-449bcaef-be79-4162-850e-aa34adf08094.png)

**Comment by sethyuan** [comment]
我安装了该主题简单看了下，没重现这个问题。你看看是否是什么别的插件导致的？或者是你的`custom.css`里有什么自定义样式导致的。

**Comment by jayus71** [comment]
因为安的插件比较多，暂时还没试出来是哪个插件的问题，在custom.css里只有以下几行代码
```
.latex-inline { margin: 0 0.2em; }
```

**Comment by sethyuan** [comment]
这句不大会有影响，我觉得需要找可能对`#app-container`有影响的插件或主题，因为工具栏是放在`#app-container`下的。要不你先查着，这个ticket我就先关了。

**Comment by jayus71** [comment]
好的好的
