### ISSUE TITLE
你好！在导出页面至text或者pdf时遇到问题

### ISSUE THREAD

**Issue by oatnoodle** [sethyuan/logseq-plugin-wrap#23]
1.在导出页面至text或者pdf时，高亮的字体会显示出原有的代码
![Snipaste_2022-08-26_18-31-13](https://user-images.githubusercontent.com/81693228/186889515-73b3996c-c779-468c-83b2-4f804873f40b.png)

2.同一句话高亮两个关键词在xmind插件里面预览只有一个正常显示
![Snipaste_2022-08-26_19-01-34](https://user-images.githubusercontent.com/81693228/186889928-ca4dbaed-164f-48a5-a7fe-450ef46226d8.png)

如图所示，这两个问题怎么办啊

**Comment by sethyuan** [comment]
1. 无解。markdown本身就不支持多颜色高亮，其实连高亮`^^`这个语法都是不标准的。导出的过程是由Logseq实现的，插件无法干预。
2. 我不知道你用的是啥，怎么用的，无法回答。

**Comment by sethyuan** [comment]
1. 是正常效果，导出文字就是会看到文本。
2. 本插件影响不到markmap的渲染；导出txt参考1.

**Comment by oatnoodle** [comment]
好的，谢谢您的帮助。
