### ISSUE TITLE
.json file shows empty

### ISSUE THREAD

**Issue by mujihuz** [sethyuan/logseq-plugin-wrap#24]
When I click on "open settings" on macOS, the firefox tab is empty: 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/86186715/190154821-94c571c4-581a-48ed-a402-b4d45cd86b35.png">

I'm totally illiterate in coding etc, so I thought "Hmm, maybe I should open it with a coding software". I installed "Whisk" from setapp and opened the file there. It is empty again: 
<img width="883" alt="image" src="https://user-images.githubusercontent.com/86186715/190155430-8d9ea412-28e5-466c-8f04-2b5293e90b52.png">

What am I doing wrong?

**Comment by sethyuan** [comment]
Open the setting file (`logseq-wrap.json`) with a text editor (Visual Studio Code recommended), replace the file's content with one of the two example settings provided in the README as a starting point. BTW, the plugin has defaults builtin, so settings are not required unless you want to do customizations on your own. It requires some programming knowledge to configure properly.

**Comment by mujihuz** [comment]
Ok I followed every step. But it doesn't seem to do anything. I tried both codes. 
for instance, this is my modification of the code: 
![image](https://user-images.githubusercontent.com/86186715/190186957-40fc7b41-9ded-41c9-b0e2-9dcf08b2d028.png)
This is how I expected it to work. but as you can see, it is not working: 
![image](https://user-images.githubusercontent.com/86186715/190187138-912d2125-f1a6-49e6-b999-df2ae07be472.png)
What am I doing wrong/missing again?

**Comment by sethyuan** [comment]
Refer to the [[Toolbar style customization]] section in README if you want to modify highlights.
