### ISSUE TITLE
Customising the icons

### ISSUE THREAD

**Issue by mujihuz** [sethyuan/logseq-plugin-wrap#25]
Is there a way to change the icons as well as to add or remove other icons? 
I would appreciate it if you could provide some friendly guides on how to do that (if it's possible) on the readme as well. 

Thanks for the amazing tool btw

**Comment by sethyuan** [comment]
I'm afraid it requires a certain amount of front-end programming knowledge.

**Comment by candideu** [comment]
> Is there a way to change the icons as well as to add or remove other icons? I would appreciate it if you could provide some friendly guides on how to do that (if it's possible) on the readme as well.
> 
> Thanks for the amazing tool btw

@mujihuz was there a particular icon/tool you needed? I'm customizing the toolbar for my plugin, and I'm happy to help 😃
