### ISSUE TITLE
能否增加快捷键：显示/不显示toolbar

### ISSUE THREAD

**Issue by tiankonganddahai** [sethyuan/logseq-plugin-wrap#27]
目前只是在配置文件中，通过true、false设置，能否做成一个快捷键，方便控制常显或者关闭。

**Comment by sethyuan** [comment]
已实现，设置里添加了 `toolbarShortcut`。也可以通过命令切换是否显示。

**Comment by tiankonganddahai** [comment]
真快呀，谢谢，感谢。

**Comment by tiankonganddahai** [comment]
谢谢先。
安装后有个问题，工具栏是垂直放置的，是那里还需要设置吗？
![image](https://user-images.githubusercontent.com/52421384/198028538-1f92736f-79aa-4dec-8150-c31561008189.png)

**Comment by tiankonganddahai** [comment]
OK了。
