### ISSUE TITLE
插件效果能否同步到移动端

### ISSUE THREAD

**Issue by susanooxyz** [sethyuan/logseq-plugin-wrap#3]
目前在使用这个插件，很高兴能满足我的一些需要。但是移动端不能正常显示，不知道能不能让移动端也和pc端效果一致。

**Comment by sethyuan** [comment]
很高兴你能喜欢这个插件。移动端目前应该只有安卓版的吧，我自己是iOS，没有设备可以调试。等iOS版出来了我再看看吧。

**Comment by susanooxyz** [comment]
现在android端也是ok的:thumbsup:
