### ISSUE TITLE
自动读取logseq本体与插件注册的快捷功能，用户自动添加和排布顺序，添加图标

### ISSUE THREAD

**Issue by aiyou9** [sethyuan/logseq-plugin-wrap#30]
能不能读取logseq本体和用户安装插件在logseq的功能，给出列表，让用户自己选择添加，以及设定图标。

读取/呼出命令中的命令，让用户选择，添加，并自主排序，接入图标库，选择喜欢的图标（感觉有些重复了，而且呼出有问题）

看大佬自己给这个插件，增加了很多功能，

obsidian中的大佬修改的插件，从原来选中后弹出，变为顶部固定工具栏
https://github.com/cumany/obsidian-editing-toolbar
原始插件：https://github.com/chetachiezikeuzor/cMenu-Plugin

**Comment by sethyuan** [comment]
我感觉这是两个插件了。Text Wrapper并不是工具条，而是自定义文字包围与替换命令，你甚至可以不使用工具条。另外系统命令执行的context各种各样，很多也与文本编辑无关，不适合放在Text Wrapper的上下文工具条里。

至于你想实现的效果，我觉得应该是做在另外一个单独的插件里。

**Comment by aiyou9** [comment]
> 我感觉这是两个插件了。Text Wrapper并不是工具条，而是自定义文字包围与替换命令，你甚至可以不使用工具条。另外系统命令执行的context各种各样，很多也与文本编辑无关，不适合放在Text Wrapper的上下文工具条里。
> 
> 至于你想实现的效果，我觉得应该是做在另外一个单独的插件里。

好的，谢谢大佬
