### ISSUE TITLE
Behaviour when clicking toolbar button multiple times

### ISSUE THREAD

**Issue by candideu** [sethyuan/logseq-plugin-wrap#32]
Hi Seth! Thank you so much for making this plugin! It saves a lot of time with formatting, and is great for people who don't know all the markdown shortcuts by heart.

I just had a small suggestion about the behaviour when people click on an icon in the toolbar. At the moment, when it's clicked on more than once, it adds the formatting template multiple times:

https://user-images.githubusercontent.com/55474996/217696885-eac23d70-23e0-4c86-950b-465e3fb8506e.mp4

However, this isn't necessarily expected or desirable. Instead, I suggest one of two behaviours:

1. The formatting is only added once, and future button presses do nothing
2. Pressing on the button toggles between adding the formatting and removing it

Here's an example with the Quill editor:

https://user-images.githubusercontent.com/55474996/217697627-c7082583-7a60-4f61-8e67-d0108a00c029.mp4

**Comment by sethyuan** [comment]
I don't think this behavior is appropriate for this plugin, as the name indicates, it's main focus is in wrapping, not styling.

**Comment by sethyuan** [comment]
Like I said before, the plugin is mainly about wrapping, not styling and it's not appropriate to apply a constraint of not being able to apply a certain wrapping twice or more. If you hit the command twice by accident, you can just undo.
