### ISSUE TITLE
"$^$^$" cannot be used as a superscript

### ISSUE THREAD

**Issue by g0267** [sethyuan/logseq-plugin-wrap#38]
"template": "$^$^$",
This template cannot be used as a superscript

**Comment by sethyuan** [comment]
"$^" is a reserved keyword for content. What is that you want to achieve? You can write `base^{sup}` for superscripts in markdown and `base_{sub}` for subscripts BTW.

**Comment by g0267** [comment]
Logseq used base^{sup},need a space,(base ^{sup})
A <sup>1</sup>B2C3,Not beautiful

**Comment by g0267** [comment]
thanks you ,i used <sup> ,not beautiful
