### ISSUE TITLE
Why not set "F2" or other single key(not a basic char") for the shortcut?

### ISSUE THREAD

**Issue by leeyaunlong** [sethyuan/logseq-plugin-wrap#39]
Why not set "F2" or other single key(not a basic char") for the shortcut?
If use "Ctrl+F2" is work.

**Comment by sethyuan** [comment]
你说的是什么的快捷键？

**Comment by leeyaunlong** [comment]
Current, I binding the alt+F2 to "wrap-pageref, it's work. 
When I try to binding "F2" for it, failed. ( I checked the logseq shortcuts list, no others use "F2").
```
  "group-ref": {
    "wrap-pageref": {
      "label": "Page ref",
      "binding": "alt+F2",
      "template": "[[$^]]",
........
```



> 你说的是什么的快捷键？

**Comment by sethyuan** [comment]
I'm not sure, this key binding process is delegated to Logseq. Can you check if you have some system level shortcuts that may be in conflict with yours?
