### ISSUE TITLE
没法清除掉cloze和双链等格式

### ISSUE THREAD

**Issue by yoghurtdewdew** [sethyuan/logseq-plugin-wrap#42]
点击清除格式的时候没法清除掉cloze格式：`{{cloze  {{cloze 测试}}}}` 没法变成 `测试`

没法清除双链：`[[测试]]` 

复杂格式没法清除链接：`[[[{{cloze  {{cloze 测试}}}}]]]()`

**Comment by sethyuan** [comment]
双链不清除是刻意的，因为它不是一种样式。

你给的那个复杂格式的例子连Logseq都渲染的不对，实际中也不会有人这样用哈。

至于cloze确实没有实现其清除功能，欢迎提PR。

**Comment by yoghurtdewdew** [comment]
好哒 所以cloze是技术方面不好实现去掉是嘛，我以为是漏掉了还是为了不影响其他的格式故意这样设置的

**Comment by sethyuan** [comment]
是的，现在没有精力去搞cloze的清除了。
