### ISSUE TITLE
request：灰色

### ISSUE THREAD

**Issue by yoghurtdewdew** [sethyuan/logseq-plugin-wrap#43]
高亮和线条希望能有灰色！比如有段话，混杂着部分解释，不想隐藏掉，又不想突出显示另一部分，又想有个对比，看着能更清晰一些

**Comment by sethyuan** [comment]
能附张效果图吗？我不是很明白你想要的效果到底是怎样的。你说的线条是啥？

**Comment by yoghurtdewdew** [comment]
就是字体颜色和高亮颜色的灰色，就是能用`[[#grey]]==测试==`和`[[$grey]]==测试==`，目前不是有高亮或改字体颜色 把内容进行突出显示嘛，我是想不突出显示但是让一部分不突出一些，如果直接cloze还得点开才能看，所以提的这个灰色的字体颜色和高亮颜色的需求，对我来说，我的用法是：字体灰色代表这部分文字不重要，高亮灰色代表这部分文字曾经重要但是我已经知道了如果以后忘了的话再回来找这个

**Comment by sethyuan** [comment]
@yoghurtdewdew 这个太定制化了，直接做在插件里不太好。不过万幸插件是支持用户自己加颜色的，请参看项目README（靠下面的部分），怎么自己做配置，怎么用CSS加颜色都有说明。
