### ISSUE TITLE
Can't install Text Wrapper

### ISSUE THREAD

**Issue by alphakode** [sethyuan/logseq-plugin-wrap#45]
Whenever I try to install this plugin, this message shows up: [`Error]<logseq-wrap> :release-channel-issue "Github API Failed(403) {\"message\":\"API rate limit exceeded for user ID 1779837.\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}"]`

Please help me to solve this issue or can you please fix the issue?

**Comment by sethyuan** [comment]
This is a Logseq issue and I can't do nothing about it. It's due to release mechanism Logseq uses. You can wait some time and then try again.

**Comment by alphakode** [comment]
The issue has been fixed by updating my flatpak packages as I am running logseq flatpak. Thank you.
