### ISSUE TITLE
The user code defined shortcut cannot work in v0.9.18

### ISSUE THREAD

**Issue by leeyaunlong** [sethyuan/logseq-plugin-wrap#50]
The user code defined shortcut cannot work in v0.9.18

v0.9.18 seems use new logical for shortcut.

**Comment by sethyuan** [comment]
What do you mean? Can you paste an example that doesn't work?

**Comment by leeyaunlong** [comment]
Here is issue point, the mouse click is work, but binding: ctrl+F2 cannot work with v.0.9.18, 
And this code is work well with  v.0.9.15.

```
{
  "disabled": false,
  "toolbar": true,
  "toolbarShortcut": "",
  "group-mod100": {
	   "repl-term": {
	    "label": "replace terms",
	    "binding": "ctrl+F2",
	    "regex": "([^、，。,]{1,})",
	    "replacement": " #$1 ",
	    "icon": "<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 32 32\" fill=\"#eee\"> <path d=\"M27.769 26.667h-9.316l3.556-7.111h-4.231v-14.222h14.222v12.871l-4.231 8.462zM24.213 23.111h1.351l2.88-5.76v-8.462h-7.111v7.111h6.436l-3.556 7.111zM9.991 26.667h-9.316l3.556-7.111h-4.231v-14.222h14.222v12.871l-4.231 8.462zM6.436 23.111h1.351l2.88-5.76v-8.462h-7.111v7.111h6.436l-3.556 7.111z\"></path></svg>"
	  }
	},
```

**Comment by sethyuan** [comment]
I think this has to be reported to Logseq, the plugin is using the SDK that Logseq provides for shortcut registration.

**Comment by leeyaunlong** [comment]
> I think this has to be reported to Logseq, the plugin is using the SDK that Logseq provides for shortcut registration.

I found the solution, the logseq new version cannot use upper case Fn key(like "ctrl+F2"), 
We need to use "ctrl+f2". 
When I change to "ctrl+f2", it's work well.
