### ISSUE TITLE
可以修改或新建高亮的命令吗？

### ISSUE THREAD

**Issue by HaomingFu** [sethyuan/logseq-plugin-wrap#51]
## 问题：
我想修改现有的高亮命令，或者新建一个命令。比如把[[#green]]命令改为[[@green]]或[[&green]]，或者用这些名称来新建高亮命令。这样可能吗？请问怎么做？谢谢！

**Comment by sethyuan** [comment]
可以的，请参照README中给出的默认配置来改。

1. 拷贝默认配置作为基础
2. 添加你自己的修改
3. 调整对应的CSS（在README的下方有给出默认CSS）

**Comment by HaomingFu** [comment]
看了README之后，我知道了如何在**现行语法**基础上增加一个命令，如新增一个黄色底色的命令：[[#yellow]]==text with yellow background==。但这个并没有真正解决我的问题。

现行语法“污染”了我的logseq数据库，比如“[[#green]]==adds an item to the page #green==”会新建page "#green"，且在本page与#green page之间建立连接，这些都不是想要的。所以我希望可以用下面的新语法（不管是新增语法或修改现行语法）来实现现有功能，如：
{green}==text with green background== 等价地实现
[[#green]]==text with green background==。

不知道您的插件支不支持新建上述语法？如支持，具体该怎么做？谢谢

**Comment by sethyuan** [comment]
@HaomingFu 这个支持不了，之所以用tag是有原因的，插件要依靠tag做标记才能识别哪里要加什么样式。

**Comment by HaomingFu** [comment]
明白，谢谢
