### ISSUE TITLE
[Bug] Incorrect export effect

### ISSUE THREAD

**Issue by jackyliu16** [sethyuan/logseq-plugin-wrap#55]
使用这个软件进行导出的时候，在类似于 `[[_green]]==STH==` 进行导出的时候，无论是官方自带的导出为，或者是导出为 PDF plugins 均无法正常实现将标记后文本导出成为正确高亮形式的效果（被解析为一般markdown高亮格式）可能需要自带一个导出功能来实现这个效果。

== ENG Translate

When using this software to export, when exporting something like '[[_green]]==STH==', neither the official built-in export as or the export to PDF plugins can normally achieve the effect of exporting the tagged text into the correct highlighted form (which is parsed into the general markdown highlight format), and you may need to have a built-in export function to achieve this effect.

Plugins Version: v0.10.3

**Comment by sethyuan** [comment]
Markdown导出有问题是因为Markdown并不支持多颜色高亮，PDF导出有问题可能是你所使用的PDF插件有问题。更完美的PDF导出建议使用Doc View Exporter插件，导出HTML文件后用浏览器打开，选择打印成PDF就可以了。

下面是一张测试效果图：

![image](https://github.com/sethyuan/logseq-plugin-wrap/assets/3410293/8b852abc-0efb-4953-b54a-b997287e0cb0)

**Comment by jackyliu16** [comment]
我测试了一下也确实是这样的，目前来看似乎只有这款插件支持完整的导出功能，包括官方的html导出实现的效果也不是很好。
