### ISSUE TITLE
安装插件后，logseq启动后页面要停留一段时间才有反应

### ISSUE THREAD

**Issue by tiankonganddahai** [sethyuan/logseq-plugin-wrap#7]
谢谢开发这么棒的插件！
有个问题想请教一下。
问题描述：
1、下载插件，安装
2、打开logseq
3、看到正常页面已经加载出来
4、点击光标准备输入文字，但是logseq界面不反应
5、要等页面显示一会（大约比不加载多5秒），才会点击光标输入。
不知道是不是插件的影响？

**Comment by sethyuan** [comment]
应该是个例，我没有收到过类似报告，我自己的使用也是正常的。你可以尝试禁止不同的插件来测试。
