### ISSUE TITLE
can't open its settings or disable it from logseq's built-in plugins menu

### ISSUE THREAD

**Issue by lef-est** [sethyuan/logseq-plugin-wrap#8]
![image](https://user-images.githubusercontent.com/9643637/158122647-b6d29c72-9014-46bd-baae-54151550528e.png)
This button does not open the corresponding file, while the setting files themselves are empty, not even including the ``` { "disabled": false }``` part, and thus I can't disable this plugin from the logseq interface.

Environment: Windows 10, logseq 0.6.3

**Comment by sethyuan** [comment]
It sounds like an issue with Logseq itself, not the plugin. BTW, you can also disable the plugin by toggling the switch on the right.

**Comment by lef-est** [comment]
> It sounds like an issue with Logseq itself, not the plugin. BTW, you can also disable the plugin by toggling the switch on the right.

I can open settings for all the other plugins though..? and actually the "thus I can't disable this plugin from the logseq interface" part is referring to the switch on the right.

**Comment by lef-est** [comment]
actually a week ago I also tried this plugin. At that time I had the same problems but I also tried manually editing its settings file, which did not work. Last week I couldn't even uninstall this plugin via the GUI --- I had to manually delete its folder. At least now that doesn't seem to problem, but I doubt manually editing the settings file would work so I haven't tried that again yet.

**Comment by sethyuan** [comment]
You should report this to the Logseq team, plugins themselves can't control installation and uninstallation. It seems that for some reasons, you files are corrupted.

**Comment by lef-est** [comment]
okay noted👌. your "TOC Generator" has been working fine for me so i thought it was weird.

**Comment by asifm** [comment]
Just wanted to share that I'm facing the same problems with the latest version (clicking on `open settings` doesn't do anything; also can't disable the plugin using the provided switch). I'm not experiencing similar problems with other plugins. For now, I'm uninstalling it. Will try at a later time.

**Comment by lef-est** [comment]
@asifm I later realized it was caused by my own mistake (a trailing comma in the settings file after making my own changes). after removing the comma or whatever syntactical error it may have, relaunch logseq and it should fine.
also cc @sethyuan if you see similar reports in the future, this could be the cause.

**Comment by Vanvangogh0318** [comment]
Have you opened its settings successfully?I have met the same problem,while i can also open the settings of other plugins appropriately.Besides,logseq will remind me that there has a conflict between the shortcuts of "Text Wrapper",as long as i finish the installation.I don't know whether it's Logseq's fault.
