### ISSUE TITLE
默认 Cloze 的改进

### ISSUE THREAD

**Issue by Crowds21** [sethyuan/logseq-plugin-wrap#9]
在 logseq 中,对于中文文本`这是{{cloze一段测试}}文本` 无法识别为 cloze.
需要变为`这是 {{cloze一段测试}} 文本`. cloze 的前后需要有一个空格. 
虽然自己也能修改,但还是建议加入默认的配置中.

**Comment by sethyuan** [comment]
有道理，默认配置已调整，另外在README中提供了另一套配置可参考。
